--- #YAML:1.0
name: Text-Templet
abstract: Lightweight Text Template Processor
version: 2.8
author:
  Denis Petrov <denispetrov@yahoo.com>
license: perl
requires:
  perl: 5.006
meta-spec:
  version: 1.3
version_from: lib/Text/Templet.pm
installdirs:  site
distribution_type: module
generated_by: Denis Petrov

